# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#011221'
foreground='#f8f8f2'
cursor='#f92672'

# Colors
color0='#011221'
color1='#f92672'
color2='#a6e22e'
color3='#f4bf75'
color4='#66d9ef'
color5='#ae81ff'
color6='#a1efe4'
color7='#f8f8f2'
color8='#75715e'
color9='#f92672'
color10='#a6e22e'
color11='#f4bf75'
color12='#66d9ef'
color13='#ae81ff'
color14='#a1efe4'
color15='#f9f8f5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
