--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#011221"
foreground="#f8f8f2"
cursor="#f92672"

-- Colors
color0="#011221"
color1="#f92672"
color2="#a6e22e"
color3="#f4bf75"
color4="#66d9ef"
color5="#ae81ff"
color6="#a1efe4"
color7="#f8f8f2"
color8="#75715e"
color9="#f92672"
color10="#a6e22e"
color11="#f4bf75"
color12="#66d9ef"
color13="#ae81ff"
color14="#a1efe4"
color15="#f9f8f5"
