#! /bin/sh
. $HOME/.cache/wal/colors.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config normal_border_color $background
bspc config active_border_color $color1
bspc config focused_border_color $color1
bspc config presel_feedback_color $color2

bspc config window_gap           40
bspc config top_padding          3

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_radius	 0


#bspc rule -a firefox border=off
bspc rule -a '*:zathura' state=tiled

# On the fly desktop renaming
$HOME/build/go/bin/btops
