#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           0
bspc config top_padding          0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_radius	     0


bspc rule -a firefox border=off
bspc rule -a '*:zathura' state=tiled

# On the fly desktop renaming
$HOME/build/go/bin/btops
